In [3]:
import copy
import torch
import numpy as np
import math

In [13]:
q = torch.Tensor([np.random.random(10),np.random.random(10),np.random.random(10), np.random.random(10), np.zeros((10,1)), np.zeros((10,1))])
k = torch.Tensor([np.random.random(10),np.random.random(10),np.random.random(10), np.random.random(10), np.zeros((10,1)), np.zeros((10,1))])
scores = torch.matmul(q, k.transpose(0,1)) / math.sqrt(10)
mask = torch.Tensor([1,1,1,1,0,0])
mask = mask.unsqueeze(1)
scores

tensor([[1.0905, 0.6730, 0.8357, 0.8548, 0.0000, 0.0000],
        [0.5524, 0.5520, 0.6604, 0.6154, 0.0000, 0.0000],
        [0.6032, 0.5920, 0.6990, 0.6567, 0.0000, 0.0000],
        [0.8572, 0.9728, 0.9671, 0.9296, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [11]:
scores = scores.masked_fill(scores==0, -np.inf)

In [12]:
scores

tensor([[0.7785, 0.6371, 0.8465, 0.8148,   -inf,   -inf],
        [0.8156, 0.6631, 0.8386, 0.8294,   -inf,   -inf],
        [0.5836, 0.7190, 0.9845, 0.7638,   -inf,   -inf],
        [0.6466, 0.5366, 0.7733, 0.5670,   -inf,   -inf],
        [  -inf,   -inf,   -inf,   -inf,   -inf,   -inf],
        [  -inf,   -inf,   -inf,   -inf,   -inf,   -inf]])

In [10]:
q.shape

torch.Size([6, 10])

In [9]:
k

tensor([[0.0360, 0.8665, 0.9652, 0.7520, 0.0320, 0.4395, 0.7705, 0.1589, 0.1866,
         0.5359],
        [0.5122, 0.5212, 0.3144, 0.5749, 0.0690, 0.3491, 0.5037, 0.5732, 0.5091,
         0.2866],
        [0.5452, 0.9535, 0.4544, 0.5494, 0.5952, 0.1282, 0.4389, 0.7857, 0.3352,
         0.1589],
        [0.9175, 0.0398, 0.8167, 0.5276, 0.0563, 0.0028, 0.6097, 0.9256, 0.3488,
         0.5466],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000]])

In [6]:
    size = 5
    atten_shape = (1, size, size)
    mask = np.triu(np.ones(atten_shape), k=1).astype('uint8')

In [7]:
mask

array([[[0, 1, 1, 1, 1],
        [0, 0, 1, 1, 1],
        [0, 0, 0, 1, 1],
        [0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0]]], dtype=uint8)

In [8]:
torch.from_numpy(mask) == 0 

tensor([[[ True, False, False, False, False],
         [ True,  True, False, False, False],
         [ True,  True,  True, False, False],
         [ True,  True,  True,  True, False],
         [ True,  True,  True,  True,  True]]])

In [9]:
def make_std_mask(tgt, pad):
    tgt_mask = (tgt !=pad) # pad masking
    tgt_mask = tgt_mask.unsqueeze(-2) # reshape (n_batch, seq_len) -> (n_batch, 1, seq_len)
    tgt_mask = tgt_mask & Variable(subsequent_mask(tgt.size(-1)).type_as(tgt_mask.data)) 
    #beat-wise 연산자... 잘 모르겠다.
    return tgt_mask

In [ ]:
make_std_mask()